/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MaterHospitalGUI.java
 *
  */

package AEMaterHospital;
/**
 *
 * @author Hamilton1
 */

public class MaterHospitalGUI extends javax.swing.JFrame {

    /** Creates new form MaterHospitalGUI */
    private PQInterface myPQueue;
    public MaterHospitalGUI() {
        myPQueue = new MyPriorityQueue();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        symptomJLabel = new javax.swing.JLabel();
        nameJText = new javax.swing.JTextField();
        symptomJText = new javax.swing.JTextField();
        numPatientsJButton = new javax.swing.JButton();
        addJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        displayJLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDisplay = new javax.swing.JTextArea();
        symptomJLabel1 = new javax.swing.JLabel();
        priorityJText = new javax.swing.JTextField();
        listJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcomeJLabel.setForeground(java.awt.Color.black);
        welcomeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeJLabel.setText("Welcome to A&E Mater Hospital");

        nameJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameJLabel.setForeground(java.awt.Color.red);
        nameJLabel.setText("Patient's name");

        symptomJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        symptomJLabel.setForeground(java.awt.Color.red);
        symptomJLabel.setText("Set priority");

        nameJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextActionPerformed(evt);
            }
        });

        numPatientsJButton.setText("No. of patients");
        numPatientsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPatientsJButtonActionPerformed(evt);
            }
        });

        addJButton.setText("Add patient to waiting list");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        removeJButton.setText("Next patient");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });

        displayJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextAreaDisplay.setColumns(20);
        jTextAreaDisplay.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDisplay);

        symptomJLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        symptomJLabel1.setForeground(java.awt.Color.red);
        symptomJLabel1.setText("Main symptoms");

        priorityJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityJTextActionPerformed(evt);
            }
        });

        listJButton.setText("Waiting patients");
        listJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(displayJLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(nameJLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(nameJText, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(symptomJLabel1)
                                            .addComponent(symptomJLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(priorityJText, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                            .addComponent(symptomJText))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(listJButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                        .addComponent(numPatientsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(removeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeJLabel)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJLabel))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(symptomJLabel1)
                    .addComponent(symptomJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(symptomJLabel)
                    .addComponent(priorityJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numPatientsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(displayJLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextActionPerformed

    private void numPatientsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPatientsJButtonActionPerformed
        // TODO add your handling code here:
        jTextAreaDisplay.append("There are " + myPQueue.size() + " patients on the waiting list\n");
    }//GEN-LAST:event_numPatientsJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        String sName, sSymptoms;
        int iPriority;
        Integer priorityINT;
        
        Patient newPatient = new Patient();
        sName = nameJText.getText();
        sSymptoms = symptomJText.getText();
        newPatient.setsName(sName);
        newPatient.setsSymptom(sSymptoms);
        
        priorityINT = Integer.valueOf(priorityJText.getText());
        iPriority = priorityINT.intValue();
        myPQueue.enqueue(iPriority,newPatient);

        jTextAreaDisplay.append(nameJText.getText() + " has been successfully added to the waiting list\n");
        nameJText.setText("");
        symptomJText.setText("");
        priorityJText.setText("");
    }//GEN-LAST:event_addJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:

        if(!myPQueue.isEmpty()){
            PQElement pqElement = (PQElement)myPQueue.dequeue();
            Patient patient = (Patient)pqElement.getPatient();
            
            jTextAreaDisplay.append("The doctor will now see " + patient.getsName() +"\n");
            jTextAreaDisplay.append("Their symptoms are: " + patient.getsSymptom()+ "\n");
            jTextAreaDisplay.append("Their priority is: " + pqElement.getiKey()+ "\n");
        }
        else
            jTextAreaDisplay.append("There are no patients waiting!\n");
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void priorityJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityJTextActionPerformed

    private void listJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listJButtonActionPerformed
        // TODO add your handling code here:
        jTextAreaDisplay.append("The patients on the waiting list are...\n");
        jTextAreaDisplay.append(myPQueue.printPQueue()+ "\n");
    }//GEN-LAST:event_listJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JLabel displayJLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDisplay;
    private javax.swing.JButton listJButton;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJText;
    private javax.swing.JButton numPatientsJButton;
    private javax.swing.JTextField priorityJText;
    private javax.swing.JButton removeJButton;
    private javax.swing.JLabel symptomJLabel;
    private javax.swing.JLabel symptomJLabel1;
    private javax.swing.JTextField symptomJText;
    private javax.swing.JLabel welcomeJLabel;
    // End of variables declaration//GEN-END:variables

}
